
# ========= Border =========
file_panel_border = '#c4c2c7'
sidebar_border = '#c4c2c7'
footer_border = '#c4c2c7'

# ========= Border Active =========
file_panel_border_active = '#E55A62'
sidebar_border_active = '#E55A62'
footer_border_active = '#E55A62'
modal_border_active = '#E55A62'

# ========= Background (bg) =========
full_screen_bg = '#160d20'
file_panel_bg = '#160d20'
sidebar_bg = '#160d20'
footer_bg = '#160d20'
modal_bg = '#160d20'

# ========= Foreground (fg) =========
full_screen_fg = '#c2b5cf'
file_panel_fg = '#c2b5cf'
sidebar_fg = '#c2b5cf'
footer_fg = '#c2b5cf'
modal_fg = '#c2b5cf'

# ========= Special Color =========
cursor = '#c2b5cf'
correct = '#CB2D5F'
error = '#9B2463'
hint = '#394E8D'
cancel = '#9B2463'
gradient_color = ['#160d20', "#665d71"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#160d20'
file_panel_top_path = '#665d71'
file_panel_item_selected_fg = '#665d71'
file_panel_item_selected_bg = '#160d20'

# ========= Sidebar Special Items =========
sidebar_title = '#c2b5cf'
sidebar_item_selected_fg = '#665d71'
sidebar_item_selected_bg = '#160d20'
sidebar_divider = '#c4c2c7'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#9B2463'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#CB2D5F'
